### ISSUE TITLE
Fastify reply functions wrongly typed

### ISSUE THREAD

**Issue by g0di** [fastify/fastify-sensible#133]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi folks,

Looking at typings for fastify reply decorations added by this library in [`httpError.d.ts`](https://github.com/fastify/fastify-sensible/blob/eafa292888cef6f6e83a078e56411902e78f049f/lib/httpError.d.ts#L103)
```typescript
// Line 103
export type HttpErrorReplys = {
  getHttpError: (code: HttpErrorCodes, message?: string) => void;
} & Record<HttpErrorNames, (msg?: string) => void>;
```
it looks like that those functions (`rep.internalServerError('')` for example) should return `void`.

However, looking at the implementation in [`index.js`](https://github.com/fastify/fastify-sensible/blob/eafa292888cef6f6e83a078e56411902e78f049f/index.js#L47)
```typescript
// Line 47
fastify.decorateReply(httpError, function (message) {
  this.send(httpErrors[httpError](message))
  return this
})
```
it looks like that the reply object is returned after calling `send` function.

Could it be possible to align the typings so I can do the following in my code without a `'await' has no effect on the type of this expression.ts(80007)
` message and ESLint being mad?
```typescript
fastify.get('/', { 
  async handler(req, rep) {
    return await rep.internalServerError('Oops')
  }
}
```
<img width="903" alt="image" src="https://user-images.githubusercontent.com/2545380/233657206-c59c4dbf-a15f-4ebc-9135-fcfac0c3bf13.png">

Thanks

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by g0di** [comment]
I'll try if I got some spare time. About tests, what kind of tests you would? Just ensuring the functions actually return the reply object and not void?

**Comment by g0di** [comment]
PR opened [here](https://github.com/fastify/fastify-sensible/pull/134)

**Comment by mcollina** [comment]
check out https://github.com/fastify/fastify-sensible/blob/master/types/index.test-d.ts
