### ISSUE TITLE
[feature] add option to share schema

### ISSUE THREAD

**Issue by sinedied** [fastify/fastify-sensible#142]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

As all errors follows the same format, it would be useful to have an option similar to what exists in @fastify/multipart to provide a shared schema for errors, for those of us who use schemas for validation/swagger.

For example, using the option:
```ts
{
  sharedSchemaId: '#httpErrors',
}
```

Would allow to reference this in all route schemas.

### Motivation

If you use schema for swagger, you'll have to write this schema in all your fastify apps.
This could be built-in in this plugin as it provides the error facilities. It would also make code most robust, in case you decide later to change the error response format, it would not break apps.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by sinedied** [comment]
Yes, I'll try to wrap up a PR in the coming weeks
