### ISSUE TITLE
`fastify` types can't be extended properly in monorepo with yarn + pnpm nodeLinker 

### ISSUE THREAD

**Issue by jbroma** [fastify/fastify-sensible#155]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

\>=4

### Plugin version

\>=5

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1

### Description

Since solution suggested in #154 was not accepted, I'm opening an issue here to find alternative solution

In environments with ~~`pnpm` and~~ `yarn` with linker: pnpm, and **inside a monorepo**, `typescript` fails to resolve the types of `fastify` and can't extend the interfaces of `fastify` properly.

During type-checking, `tsc` fails with the following error:
Typescript should fail with the following error:
```
index.ts:8:9 - error TS2339: Property 'notFound' does not exist on type 'FastifyReply<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, ... 4 more ..., unknown>'.
8   reply.notFound();
          ~~~~~~~~

Found 1 error in index.ts:8
```

As a side-note: in local environment this can be fixed by adding the following `.yarnrc.yml`:
```yaml
packageExtensions:
  "@fastify/sensible@*":
    peerDependencies:
      fastify: "*"
```

### Steps to Reproduce

Reproduction repository: https://github.com/jbroma/ffy-sensible-repro

Steps to reproduce:
1. Clone the repository
2. Install dependencies with `yarn`
3. Run `yarn typecheck`

### Expected Behavior

Fastify types are properly extended

**Comment by jbroma** [comment]
Hi @mcollina, thank you for your prompt response

I have rushed a little bit with reproduction and did not account for all the factors included (monorepo environment) and also made an incorrect assumption about `pnpm` having the same behaviour.

I've modified the reproduction repo accordingly to include your change and the monorepo setup where it still doesn't work properly. Adjusted issue title and description as well.

I've also included a branch with `pnpm` as a package manager to show that it does work correctly [there](https://github.com/jbroma/ffy-sensible-repro/tree/pnpm)

I'm now begining to think this might be an issue with `yarn` and it's pnpm nodeLinker and not with the package.

**Comment by mcollina** [comment]
I'm not exactly sure what's happening, but it looks like a bug in yarn 4. Yarn v4 should create a compatible structure with what npm and pnpm create.

By the numbers reported by https://github.com/nodejs/node/issues/50963#issuecomment-1885881236, only yarn v1 has market penetration, and I'm not sure we should actually do anything to support this variation of module resolution.

**Comment by jbroma** [comment]
Yeah I agree that it's probably a bug in yarn v4, I'll close this one as it's not related to `@fastify/sensible` itself. Thanks for your time @mcollina
