### ISSUE TITLE
Support for fastify v5

### ISSUE THREAD

**Issue by mrlectus** [fastify/fastify-sensible#169]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I get this error when using v5 fastify
FastifyError [Error]: fastify-plugin: @fastify/sensible - expected '4.x' fastify version, '5.0.0' is installed

**Comment by Eomm** [comment]
Just released the new version.
Try to install this plugin's v6
