### ISSUE TITLE
`fastify.assert` in `setTimeout` crashes `fastify` server

### ISSUE THREAD

**Issue by philipp-tailor** [fastify/fastify-sensible#180]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.3

### Plugin version

5.1.1

### Node.js version

20.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

15.1.1

### Description

Running `fastify.assert` with a failing assertion inside of `setTimeout` appears to crash the `fastify` server.

Crashes the server:
```js
fastify.get(
	'/',
	{},
	async function (request, reply) {
		setTimeout(() => {
			fastify.assert(false, 404, 'Not found.')
		}, 1000)
		await new Promise(resolve => {
			setTimeout(resolve, 5000)
		})
		return 'ok'
	}
)
```

Usage inside the root level of the route handler of the server does not crash the server:
```js
fastify.get(
	'/',
	{},
	async function (request, reply) {
		fastify.assert(false, 404, 'Not found.')
		return
	}
)
```

Using `reply` directly also does not crash the server:
```js
fastify.get(
	'/',
	{},
	async function (request, reply) {
		setTimeout(() => {
			return reply.code(400).send('Not found.')
		}, 1000)
		await new Promise(resolve => {
			setTimeout(resolve, 5000)
		})
		return 'ok'
	}
)
```

### Link to code that reproduces the bug

https://stackblitz.com/edit/stackblitz-starters-1gmxdpnz?file=index.js

### Expected Behavior

`fastify.assert` would - at least if the route handler is still being executed - ideally behave just like when executed at the route handler's root level. If there's some reason why `fastify.assert` can't be expected to work inside `setTimeout`, there could be an error / warning explaining the limitation.

**Comment by climba03003** [comment]
Here is an example on what you are doing, 
```
try {
  setTimeout(() => {
    throw Error('you can\'t catch me')
  })
} catch (err) {
  console.log('unreachable')
}
```

You can never have outer scope catching the error in a callback, that is the simple reason on why the server crashing. Because you have a uncatchable error throwing.
I would say it is a basic JavaScript knowledge, not sure if it should be added to document.

**Comment by philipp-tailor** [comment]
🤦🏼 Of course, my bad. Somehow I assumed that `fastify.assert` was a light abstraction on top of `return reply.code(xxx).send(msg)`, and didn't expect it throw an error, but I should have re-read the `README` / checked the source code to verify the assumption when it became apparent that that's not how the system behaved. Thank you for taking the time to explain it to me even when it was my oversight.
