### ISSUE TITLE
@types/node specified in dependencies

### ISSUE THREAD

**Issue by sergiz** [fastify/fastify-sensible#30]
https://github.com/fastify/fastify-sensible/blob/07247385fd69f73c28069ddc95659e8f1e331082/package.json#L32

Shouldn't this be in devDependencies?

**Comment by mcollina** [comment]
Yes it should! Would you like to send a PR?

**Comment by sergiz** [comment]
https://github.com/fastify/fastify-sensible/pull/31 done
