### ISSUE TITLE
Make it possible to add 'properties' to httpErrors

### ISSUE THREAD

**Issue by khendrikse** [fastify/fastify-sensible#37]
## 🚀 Feature Proposal

When using `server.httpErrors` it would be nice to be able to also pass properties like you can do in the `createError([status], [message], [properties])` options of `http-errors`. If this is not possible, maybe another option would be to have it expose `createError()` itself in case one might want to do:

```
server.httpErrors.createError(([status], [message], [properties])
```

## Motivation

When using this library, a bit reason could be that one wants to use the httpErrors functionality. But right now it is only possible to parse along a message, while for some errors additional data might be required. 

## Example

Please provide an example for how this feature would be used.

```
server.httpErrors.badRequest(([status], [message], [properties])
```
or

```
server.httpErrors.createError(([status], [message], [properties])
```

**Comment by mcollina** [comment]
Those come from the `http-errors` module, they should be supported already: https://www.npmjs.com/package/http-errors.
Maybe we are messing that up somehow?

**Comment by khendrikse** [comment]
@mcollina I could have not seen it properly :) but what I noticed is that it seems that we can only pass one argument, being the `message`. 

Looking at the implementation [here](https://github.com/fastify/fastify-sensible/blob/master/lib/httpErrors.js#L20) I got the idea that it does not support passing anything else?

**Comment by mcollina** [comment]
Good spot! Could you send a PR to add the extra parameters?

**Comment by khendrikse** [comment]
@mcollina I'll do my best :)

**Comment by khendrikse** [comment]
@mcollina I see that when using `new createError[code || name]([msg]))` it is only possible to pass a message [like described here](https://www.npmjs.com/package/http-errors#new-createerrorcode--namemsg)

So I think the only thing we can do is add to the documentation that the error messages exposed by `fastify-sensible` follow that pattern, or expose a method like `server.httpErrors.createError()` that will follow, and expose the [`createError([status], [error], [properties])`](https://www.npmjs.com/package/http-errors#createerrorstatus-error-properties) method.

But I don't know if we want to expose that?

**Comment by khendrikse** [comment]
Fixed!
