### ISSUE TITLE
How to override custom error handler

### ISSUE THREAD

**Issue by robinvdvleuten** [fastify/fastify-sensible#4]
I like the request methods this plugin adds, but how would like to handle the errors myself. How do I override the custom error handler? I've tried to add it after and before registering this plugin, but it never gets called;

```js
fastify.setErrorHandler(function (error, request, reply) {
  // Never called here...
})

fastify.register(require('fastify-sensible'))

fastify.setErrorHandler(function (error, request, reply) {
  // Never called here...
})
```

**Comment by delvedor** [comment]
Hi! The plugins are registered asynchronously, while the custom error handler is not.

This should fix your issue :)
```js
fastify
  .register(require('fastify-sensible'))
  .after(() => {
    fastify.setErrorHandler(function (error, request, reply) {
      reply.send(error)
    })
  })
 ```

**Comment by delvedor** [comment]
I've just added a test about this :)
https://github.com/fastify/fastify-sensible/blob/535039664e5520b82aa0fa10c0194984a969265f/test/errorHandler.test.js#L108-L136

**Comment by robinvdvleuten** [comment]
Thanks, that works indeed! Still trying to get my head around Fastify's async plugin structure 🙃

**Comment by delvedor** [comment]
No problem, if you have some question open an issue in [fastify/help](https://github.com/fastify/help) :)

**Comment by Roms1383** [comment]
Reading your case I was wondering : is it possible to specify mutliple error handlers (via `setErrorHandler(...)` inside plugins and on main `fastify` instance) and deliberately pass on to the next handler ?
e.g : imagine one plugin `fastify-boom` and another one `fastify-joi` : in the first one it handles the error only if `error.isBoom` and in the second one only if `error.isJoi`.
I tried already but it seems no matter which error handler get called, it has to `reply.send(...)` something or it get stucked there.

**Comment by delvedor** [comment]
Hi @Roms1383!
No, you can't declare a "chain" of error handlers, but you can build it inside a single one!
Take a look at how we built our hook runner ;)
https://github.com/fastify/fastify/blob/c9f6ba92788c1ef70fb24ab4bb34a5d58f433dde/lib/hooks.js#L60-L84

**Comment by Roms1383** [comment]
Ha ! That's what I ended up doing ^^
But wouldn't it be a cool feature in the future ?

**Comment by delvedor** [comment]
Feel free to open a feature request in the main repo, where we can discuss more :)

**Comment by mcollina** [comment]
I think we should remove the error handler from this module, or provide an option to disable it.

**Comment by stefanO2602** [comment]
I have a follow-up question regarding overriding the custom error handler. 

I´m using i18-next and want to customize my error messages in a custom setErrorHandler. Here are my plugin registration from top to bottom.

`app.register(i18nextMiddleware.plugin, { i18next })`;

By registering this plugin I´ll get the t() method attached to the request object (I can access this in preHandler and handler hooks without any problem).

`app.register(routes, { prefix: '/api/v1' });`

`app.setErrorHandler((error, request, reply) => {
        console.log('request.t: ', request.t);
        reply.send(error);
    });`

Once I generate an error (e.g. validation error) this error is passed to my custom handler where I want to localize the error message with the t() method of the registered i18next plugin. This is were I get _undefined_ for calling request.t() as it is not registered yet is suppose.
I´ve also tried to do the setErrorHandler in an after call of the i18next registering part, as the setErrorHandler is sync and registering async.

Any tips for solving the issue? Thank you very much in advance!
