### ISSUE TITLE
Add request.is() helper

### ISSUE THREAD

**Issue by robinvdvleuten** [fastify/fastify-sensible#5]
I've added a helper in my projects to check what kind of type the request is in a similar way Express does it with [jshttp/type-is](https://npm.im/type-is);

```js
const typeis = require('type-is')

fastify.decorateRequest('is', function (types) {
  return typeis(this.raw, Array.isArray(types) ? types : [types])
})
```

As this plugin already contains some other helpers from jshttp packages, maybe this would be a nice addition as well?

**Comment by robinvdvleuten** [comment]
The `jshttp/accepts` package checks the `Accept` header and `jshttp/type-is` checks the `Content-Type` header. So `request.is('json')` for example will return true when an user submits a JSON payload.

**Comment by delvedor** [comment]
Awesome, would you mind open a pr?
