### ISSUE TITLE
`to` errors should have customizable type arguments or inference

### ISSUE THREAD

**Issue by wldcordeiro** [fastify/fastify-sensible#60]
## 🐛 Bug Report

The type used for the error is the plain `Error` type so if you have a different error like something from `got` where it has properties like `code` it throws errors. You can cast the error as your particular type but it'd be nice to be able to provide the type argument like you can for the data you expect.

## To Reproduce

```ts
const [someError, data] = await app.to(someFuncWithCustomError(arg))

if (someError.customProperty) { // oh no TS no likey!
}
```

## Expected behavior

Either a way to provide explicit typing or proper inference

```ts
// inference
const [someError, data] = await app.to(someFuncWithCustomError(arg))

if (someError.customProperty) { 
}

// explicit
const [someError, data] = await app.to<MyData, MyError>(someFuncWithCustomError(arg)) // suggestion swap type args to match func args with error type first?

if (someError.customProperty) { 
}
```

## Your Environment

- *node version*: 14
- *fastify version*: >=3.15.0
- *os*: Linux/Docker run images on Mac dev box

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by wldcordeiro** [comment]
@mcollina perhaps, it wouldn't be too large of a code change. Curious about this though as it would be a semantic major version change if I made this type change but it would match the function signature more closely too.

> suggestion swap type args to match func args with error type first?

**Comment by mcollina** [comment]
I think implicit is better, but explicit is also ok.


cc @fastify/typescript
