### ISSUE TITLE
do not specify an error handler

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-sensible#8]
Why is an error handler included?

https://github.com/fastify/fastify-sensible/blob/e08cfc48b4bee3994f20ea68842d5d627fb053c5/index.js#L39

**Comment by delvedor** [comment]
It is [explained](https://github.com/fastify/fastify-sensible#custom-error-handler) in the documentation! :)
If needed, we can add an option to disable it.

**Comment by cemremengu** [comment]
Landed in #16
