### ISSUE TITLE
Expose errors at package level 

### ISSUE THREAD

**Issue by eduardhasanaj** [fastify/fastify-sensible#86]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I am writing some REST API and I really enjoyed this package.
However, I am feeling the need to offload the business logic from the handler and handle it in some objects with service pattern. At this layer I do not want to access fastify app.
My proposal is to expose http errors at package level so we can use them anywhere we want without having a fastify instance.

### Motivation

We need to be able to use this errors anywhere we want without having access to a fastify instance.

### Example

For example:
```
import { httpErrors } from 'fastify-sensible'
```

**Comment by mcollina** [comment]
Why couldn't just use the `http-errors` module?

**Comment by eduardhasanaj** [comment]
@mcollina That's definitely possible. I just missed it when I read source code.
Thank you.
I am closing this.
