### ISSUE TITLE
`createError` function does not return custom properties

### ISSUE THREAD

**Issue by JonasHiltl** [fastify/fastify-sensible#89]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

3.1.0

### Node.js version

v14.17.6

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I'm trying to return a custom property from an Http Error that I can use to Internationalize the error in the frontend. So just like a shorthand for the message.

```typescript
throw fastify.httpErrors.createError(
  400,
  "The provided Email is already taken",
  { displayError: "emailTaken" }
);
```

But if the error gets triggered it still doesn't return the custom property `displayError`. 
Below is the returned body:
```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Test"
}
```

### Steps to Reproduce

The below route will not return the custom property in the error response.

```typescript
fastify.post("/", async function (req, reply) {
  throw fastify.httpErrors.createError(
    400,
    "The provided Email is already taken",
    { displayError: "emailTaken" }
  );
});
```

### Expected Behavior

I expect an Error response that is defined through the `createError` function with custom properties to also return them.

**Comment by mcollina** [comment]
I think you'd need to specify a custom error handler for that. The default implementation will eliminate any other properties.

**Comment by kgoedecke** [comment]
@JonasHiltl how did you end up solving this?

**Comment by Eomm** [comment]
Now you can use https://github.com/fastify/fastify-error
