### ISSUE TITLE
use `http-errors` library

### ISSUE THREAD

**Issue by davidmarkclements** [fastify/fastify-sensible#9]
this will be useful for consistent errors in other official fastify libs, 
example: 
https://github.com/fastify/fastify-jwt/blob/master/jwt.js#L10
https://github.com/fastify/fastify-jwt/blob/master/jwt.js#L128

**Comment by mcollina** [comment]
I definitely agree. We should expose `require('http-errors').createError` instead.

**Comment by delvedor** [comment]
Honestly, I don't recall why I did this; there was I reason :P
If you have time to open a pr and fix this please do!
