### ISSUE TITLE
www-authenticate at UnauthorizedError

### ISSUE THREAD

**Issue by matthyk** [fastify/fastify-sensible#92]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

If the server responds with a 401 status code, [RFC 7235](https://datatracker.ietf.org/doc/html/rfc7235#section-3.1) requires that the www-authenticate header be included. So it should be possible for the developers to set the values for the authentication type and the realm once, and all 401 errors should then contain the www-authenticate header with the appropriate values.

### Motivation

This feature would make it much easier for developers to develop RFC compliantly. It would be optional to set these values, so using the plugin would not change if you don't want to use this feature.

### Example

```javascript
const fastify = require('fastify')()
const sensible = require('fastify-sensible')

fastify.register(sensible, {
  authenticationType: 'Basic',
  realm: 'MyApp'
})

// response would contain header www-authenticate with value 'Basic realm=MyApp'
fastify.get('/', async (req, res) => {
  throw this.httpErrors.unauthorized()
})
```

**Comment by mcollina** [comment]
This behavior is implemented in https://www.npmjs.com/package/fastify-basic-auth. Why adding it to this module?

**Comment by matthyk** [comment]
I think this is a feature for which you should not need to install fastify-basic-auth. For example, if you use an external authentication provider, you don't need fastify-basic-auth but you may still need the functionality to automatically set the www-authenticate header.

**Comment by Eomm** [comment]
What about?

```
throw this.httpErrors.unauthorized({
  authenticationType: 'Basic',
  realm: 'MyApp'
})
```

**Comment by matthyk** [comment]
I think this approach is less efficient and more repetitive than specifying the *authenticationType* and *realm* when registering the plugin. And fastify-basic-auth also uses this approach.

**Comment by mcollina** [comment]
> I think this is a feature for which you should not need to install fastify-basic-auth. For example, if you use an external authentication provider, you don't need fastify-basic-auth but you may still need the functionality to automatically set the www-authenticate header.

I don't understand this use case. Installing a module is cheap, you can use how many you need.
