### ISSUE TITLE
Maybe pagination?

### ISSUE THREAD

**Issue by bacloud22** [fastify/fastify-sensible#98]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'm trying to move from Express to Fastify. 
I have been doing pagination in other projects simply as a middleware on allroutes (app level) to grab the requested page, then grab and use number of page (as an offset always in a query)

Just an example:

https://github.com/bacloud22/Classified-ads-48/blob/cee17333c9bebd18eb83564dd5d5080bbe572fcb/sexpress.js#L116

Used here

https://github.com/bacloud22/Classified-ads-48/blob/cee17333c9bebd18eb83564dd5d5080bbe572fcb/lib/routes/listings.js#L39

As you can see the logic here is very simple and maybe no customisation is needed
Ps: I can't work on this as I need to learn more about the philosophy here 😄 

Thanks

**Comment by jsumners** [comment]
Such a thing is an application implementation detail. It is not a generic feature for a module such as this one.
